dependencies {
    api project(':cip:cip8')
    api project(':core')
    api(libs.co.nstant.in.cbor)
    testImplementation(project(':test-support')) {
        exclude group: 'net.jqwik'
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'Cardano Client CIP30'
                description = 'Cardano Client Lib - CIP30 Implementation'
            }
        }
    }
}
