package com.bloxbean.cardano.client.txflow.stream;

import com.bloxbean.cardano.client.txflow.FlowStep;
import com.bloxbean.cardano.client.txflow.TxFlow;

import java.util.ArrayList;
import java.util.List;

/**
 * MVP planner: one generated bounded flow per window, one item per generated step.
 * <p>
 * This planner performs batching and status mapping. It does not merge multiple
 * items into one Cardano transaction.
 */
public final class DefaultTxStreamPlanner implements TxStreamPlanner {
    /**
     * Create the default stream planner.
     */
    public DefaultTxStreamPlanner() {
    }

    /**
     * Convert all items in the window into one generated bounded flow.
     *
     * @param context stream planning context
     * @return stream plan with one generated flow
     */
    @Override
    public TxStreamPlan plan(TxStreamPlanningContext context) {
        if (context.getItems().isEmpty()) {
            throw new IllegalArgumentException("Cannot plan an empty stream batch");
        }

        String flowId = context.getStreamId() + "-" + context.getBatchId() + "-flow-1";
        TxFlow.Builder flowBuilder = TxFlow.builder(flowId)
                .withDescription("Generated by TxFlowStream " + context.getStreamId());
        List<TxStreamPlannedItem> plannedItems = new ArrayList<>();

        int index = 0;
        for (TxWorkItem item : context.getItems()) {
            String generatedStepId = "item-" + index + "-" + safeId(item.getItemId());
            FlowStep step = item.toFlowStep(generatedStepId);
            flowBuilder.addStep(step);
            plannedItems.add(new TxStreamPlannedItem(item.getItemId(), step.getId()));
            index++;
        }

        List<TxStreamPlannedFlow> flows = List.of(new TxStreamPlannedFlow(flowBuilder.build(), plannedItems));
        return new TxStreamPlan(context.getBatchId(), flows);
    }

    private String safeId(String value) {
        String sanitized = value.replaceAll("[^A-Za-z0-9_.-]", "-");
        return sanitized.isEmpty() ? "item" : sanitized;
    }
}
