package com.bloxbean.cardano.client.txflow.stream;

import com.bloxbean.cardano.client.txflow.TxFlow;
import lombok.Getter;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * One bounded flow generated by the stream planner.
 */
@Getter
public final class TxStreamPlannedFlow {
    private final TxFlow flow;
    private final List<TxStreamPlannedItem> items;

    /**
     * Create a planned bounded flow and its item mappings.
     *
     * @param flow generated bounded flow
     * @param items item-to-step mappings for this generated flow
     */
    public TxStreamPlannedFlow(TxFlow flow, List<TxStreamPlannedItem> items) {
        this.flow = flow;
        this.items = Collections.unmodifiableList(new ArrayList<>(items));
    }
}
