package com.bloxbean.cardano.client.txflow.stream;

import lombok.Getter;

/**
 * Point-in-time stream counters.
 * <p>
 * Counts are intended for lightweight observability and are not a replacement
 * for durable stream state.
 */
@Getter
public final class TxStreamStats {
    private final long acceptedItemCount;
    private final long plannedItemCount;
    private final long submittedItemCount;
    private final long confirmedItemCount;
    private final long failedItemCount;
    private final long cancelledItemCount;
    private final long batchCount;
    private final long generatedFlowCount;
    private final int pendingBufferSize;
    private final int currentWindowSize;

    /**
     * Create a stream statistics snapshot.
     *
     * @param acceptedItemCount number of items accepted by the stream
     * @param plannedItemCount number of items assigned to generated flow steps
     * @param submittedItemCount number of items whose generated transactions were submitted
     * @param confirmedItemCount number of items confirmed by bounded-flow execution
     * @param failedItemCount number of items that reached a failed terminal status
     * @param cancelledItemCount number of items that reached a cancelled terminal status
     * @param batchCount number of batches/windows created by the stream
     * @param generatedFlowCount number of bounded flows generated by planners
     * @param pendingBufferSize number of accepted items waiting in the stream buffer
     * @param currentWindowSize number of items currently collected in the open window
     */
    public TxStreamStats(long acceptedItemCount,
                         long plannedItemCount,
                         long submittedItemCount,
                         long confirmedItemCount,
                         long failedItemCount,
                         long cancelledItemCount,
                         long batchCount,
                         long generatedFlowCount,
                         int pendingBufferSize,
                         int currentWindowSize) {
        this.acceptedItemCount = acceptedItemCount;
        this.plannedItemCount = plannedItemCount;
        this.submittedItemCount = submittedItemCount;
        this.confirmedItemCount = confirmedItemCount;
        this.failedItemCount = failedItemCount;
        this.cancelledItemCount = cancelledItemCount;
        this.batchCount = batchCount;
        this.generatedFlowCount = generatedFlowCount;
        this.pendingBufferSize = pendingBufferSize;
        this.currentWindowSize = currentWindowSize;
    }
}
