dependencies {
    api project(':common')
    api project(':transaction-spec')
    testImplementation(project(':test-support')) {
        exclude group: 'net.jqwik'
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'Cardano Client Core Api module'
                description = 'Cardano Client Lib - Core Api Module'
            }
        }
    }
}
