dependencies {
    api project(':common')
    api project(':crypto')
    api project(':common-spec')

    implementation(libs.guava)
    testImplementation(project(':test-support')) {
        exclude group: 'net.jqwik'
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'Cardano Client Lib Address'
                description = 'Address generation for Cardano blockchain'
            }
        }
    }
}
