package com.bloxbean.cardano.client.plutus.annotation.processor.util.naming;

/**
 * Strategy interface for converting CIP-53 blueprint type names to valid Java identifiers.
 *
 * CIP-53 blueprints can be generated by various languages and tools, each with different
 * naming conventions. This interface provides a generic way to convert any blueprint
 * type name to a valid Java identifier.
 *
 * Common patterns found in blueprints:
 * - Dollar signs and underscores: List$ByteArray, Tuple$Int_Int
 * - Angle brackets (generics): List<Int>, Option<Data>
 * - Forward slashes (module paths): aiken/crypto/Hash, cardano/address/Credential
 * - Tildes (escaped slashes): types~1order~1Action
 *
 * Implementations must ensure all output strings are valid Java identifiers.
 */
public interface NamingStrategy {

    /**
     * Converts a string to camel case format suitable for class names.
     * Output must be a valid Java identifier starting with uppercase.
     *
     * @param value the input string (may contain special characters)
     * @return a valid Java identifier in PascalCase format
     */
    String toClassName(String value);

    /**
     * Converts a string to camel case format.
     * Output must be a valid Java identifier.
     *
     * @param value the input string (may contain special characters)
     * @return a valid Java identifier in camelCase format
     */
    String toCamelCase(String value);

    /**
     * Converts the first character of a string to uppercase.
     *
     * @param value the input string
     * @return the string with first character uppercase
     */
    String firstUpperCase(String value);

    /**
     * Converts the first character of a string to lowercase.
     *
     * @param value the input string
     * @return the string with first character lowercase
     */
    String firstLowerCase(String value);

    /**
     * Sanitizes a string to be a valid Java identifier by removing or replacing
     * invalid characters. This is the core method that handles version-specific
     * character transformations.
     *
     * @param value the input string (may contain special characters)
     * @return a valid Java identifier
     */
    String sanitizeIdentifier(String value);

    /**
     * Converts a package name to valid Java package format (lowercase, no special chars).
     *
     * @param packageName the input package name
     * @return a valid Java package name
     */
    String toPackageNameFormat(String packageName);

    /**
     * Unescapes JSON Pointer escape sequences according to RFC 6901.
     *
     * <p>JSON Pointer (RFC 6901) is used in JSON Schema $ref paths to reference definitions.
     * Only two escape sequences are defined:
     * <ul>
     *   <li><b>~0</b> represents a literal tilde (~) character</li>
     *   <li><b>~1</b> represents a literal forward slash (/) character</li>
     * </ul>
     *
     * @param value the string potentially containing JSON Pointer escape sequences
     * @return the unescaped string
     * @see <a href="https://tools.ietf.org/html/rfc6901">RFC 6901 - JSON Pointer</a>
     */
    String unescapeJsonPointer(String value);

}
