package com.bloxbean.cardano.client.transaction.spec.cert;

public enum CertificateType {
    STAKE_REGISTRATION, STAKE_DEREGISTRATION, STAKE_DELEGATION, POOL_REGISTRATION, POOL_RETIREMENT, GENESIS_KEY_DELEGATION,
    MOVE_INSTATENEOUS_REWARDS_CERT
}
