version: '1.0'
variables:
  owner_address: __runtime__
  bootstrap_tx: __runtime__
  network_id: 0
  logic_reward_address: __runtime__
extensions:
  pt:
    extension: programmable-token
    schema_version: '1'
    protocol: cip-113
    contract_version: 0.5.0-alpha.2
    deployment:
      network: ${network_id}
      bootstrap_tx: ${bootstrap_tx}
context:
  fee_payer: ${owner_address}
transaction:
  - tx:
      from: ${owner_address}
      intents:
        - type: stake_registration
          stake_address: ${logic_reward_address}
