dependencies {
    api project(':common')
    api project(':crypto')
    testImplementation(project(':test-support')) {
        exclude group: 'net.jqwik'
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'Cardano Client Spec Common'
                description = 'Cardano Client Lib - Common Spec classes used in other spec modules'
            }
        }
    }
}
