package com.bloxbean.cardano.client.quicktx;

enum DepositRefundType {
    STAKE_KEY_REGISTRATION,
    STAKE_KEY_DEREGISTRATION,
    DELGATION,
    WITHDRAWAL,
    POOL_REGISTRATION,
    POOL_RETIREMENT,
    DREP_REGISTRATION,
    DREP_DEREGISTRATION,
    GOV_ACTION
}
